# Generated by Django 3.1 on 2021-04-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_comment_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sex',
        ),
    ]
